name: 1.0

trigger:
  - development

variables:
  name: devops
  frase: Hello

pool:
  vmImage: ubuntu-latest

jobs:
  - job: trabajo1
    steps:
      -script: echo "$(frase). $(name)"

  - job: trabajo2
    steps:
      - script: echo "Angel"
       