name: 1.0

trigger:
  - development

variables:
  name: devops
  frase: Hello

pool:
  vmImage: ubuntu-latest

stages: 
  - stage: Build
    jobs:
    - job: BuildJob
      steps: 
      - script: echo "Compilando!"
      - bash: |  
          echo This multiline script always runs in bash
          echo Even on windows machines 
      - pwsh: | 
          Write-Host "blah blah"
          Write-Host "bbbb"

  - stage: Test
    jobs:
      - job: testOnWindows
        steps:
        - task: Mytask
          displayName: task_name
          timeoutInMinutes: 120
          inputs: 
          solution: '**\*.sln'
        
      - job: testOnLinux
        steps:
        - script: echo Test on Linux 

  - stage: Deploy
    jobs: 
      - job: Deploy
        steps:
        - script: echo Deploying the code 
       